[package]
name = "ninarust_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.9"
ic-cdk = "0.11.1"
ic-cdk-macros = "0.7.1"  # Add this line
ic-cdk-timers = "0.4.0"
serde = "1.0.188"
serde_bytes = "0.11.12"
hex = "0.4.3"
sha3 = "0.10.8"